#  ____                           _          _   _   ___ 
# |  _ \    ___   _ __     __ _  (_)  _ __  | | | | |_ _|
# | |_) |  / _ \ | '_ \   / _` | | | | '__| | | | |  | | 
# |  _ <  |  __/ | |_) | | (_| | | | | |    | |_| |  | | 
# |_| \_\  \___| | .__/   \__,_| |_| |_|     \___/  |___|
#                |_|                                     
#           by fernanACM
# Repair and customize your item names with RepairUI, for PocketMine-MP 5.0 servers

# DO NOT TOUCH!
config-version: "1.0.0"
# Plugin prefix
Prefix: "&l&f[&dRepairUI&f]&8»&r "
# Languages
# "eng", // English
# "spa", // Spanish
# "ger", // German
# "indo", // Indonesian
# "vie" // Vietnamese
language: eng
# Usa economyapi, bedrockeconomy, xp
Economy: 
  provider: bedrockeconomy
# ==(SETTINGS)==
Settings:
  Use:
    # Use "true" or "false" to interact with the anvil
    anvil: true
  Commands:
    # Use "true" or "false" to run the command
    # RepairAll command; /repair all
    all: true
    # Use "true" or "false" to run the command
    # RepairHand command: /repair hand
    hand: true
    # Use "true" or "false" to run the command
    # RepairAll command; /repair rename <name>
    rename: true
    # Use "true" or "false" to run the command
    # RepairAll command; /repair lore <lore>
    lore: true

# ==(REPAIR COST)==
RepairCost:
  # Repair mode
  Repair:
    # Put the amount of money cost to repair the items
    money-cost: 30
    # Put the amount of experience cost to repair the items
    xp-cost: 10
    # Damage repair mode. The price will be multiplied by the damage of the item. 
    # IT IS RECOMMENDED TO PUT THE PRICE LOW IF THIS OPTION IS CURRENT.
    # Use "true" or "false" to enable/disable this option
    damage-mode: false
  # Lore mode
  Lore:
    # Put the amount of money cost to change the lore of the items
    money-cost: 60
    # Put the amount of experence cost to change the lore of the items
    xp-cost: 20
  # Rename mode
  Rename:
    # Put the amount of money cost to change the name of the items
    money-cost: 50
    # Put the amount of experence cost to change the name of the items
    xp-cost: 20